#+TITLE: Alloy
#+DATE: [2021-05-23 Sun]

Exercises in chapter 3 of /Software Abstractions/.
* A.1.1 Properties of Binary Relations

#+begin_src alloy
module example

run {
  let Univ = univ - Int | some r: Univ -> Univ {
    some r         -- non-empty
    r.r in r       -- transitive
    no r & iden    -- irreflexive
    ~r in r        -- symmetric
    ~r.r in iden   -- functional
    r.~r in iden   -- injective
    Univ in r.Univ -- total
    Univ in Univ.r -- surjective
  }
} for 4
#+end_src

No relation r satisfies all these constraints at the same time, and the Alloy analyzer says so ("No instance found. Predicate may be inconsistent."). Removing some constraints starts to show corresponding relations. I was surprised that univ seems to contain integers [-8..7], instead of just the atoms Univ0-Univ3 (since I request max 4 atoms in the universe). I still don't know why, but hence why I've defined Univ to remove the integers.

Removing just transitive. There are two solutions, r_1={(Univ0,Univ1),(Univ1,Univ0)} and r_2={(Univ0,Univ3),(Univ3,Univ0),(Univ1,Univ2),(Univ2,Univ1)}. I was expecting more instances (one with a tuple (Univ0,Univ2) for example), however asking for more instances (Command-N), yields, "There are no more satisfying instances. Note: due to symmetry breaking and other optimizations, some equivalent solutions may have been omitted.". Which is spot on, ie why I don't see a relation containing (Univ0,Univ2). Awesome.

Removing just irreflexive. Four instances, all of which are included in identity.

Removing just symmetric. No instance with the remaining constraints.

Removing just functional. No instance.

Removing just injective. No instance.

Removing just total. No instance.

Removing just surjective. No instance.

Actually no relation other than the empty relation seems to be at the same time transitive, irreflexive, and symmetric. Hence why no instance for the last four tests.

Update. The run syntax seems to have the more general form "run { ... } for N Set1, M Set2", where N and M indicate how many atoms Set1 and Set2 each have. The syntax "run { ... } for N" seems to be shorthand for "run { ... } for N Univ". The following seems to work as well to remove integers (ie without having to define Univ as above):

#+begin_src
run {
  some r: univ -> univ {
    ...
  }
} for 4 Univ, 0 Int  -- confusingly univ must be capitalized here
#+end_src

Yet another way:

#+begin_src
run {
  some r: univ -> univ {
    ...
  }
} for 4 but 0 Int
#+end_src

The [[https://alloy.readthedocs.io/en/latest/language/sets-and-relations.html#integers][documentation]] explains that the scope for Int defaults to 3, explaining why [-2^3..2^3-1] is part of univ. Showing the parse tree (from the menu) indicates that module integer is opened automatically.

** Trying out on my own

A relation in a 4-element universe where every element is related to every other element (including itself):

#+begin_src
module example

run {
  some r: univ -> univ {
    all s,t: univ | s -> t in r
  }
} for exactly 4 Univ, 0 Int
#+end_src

First I failed using #r = 16 (ie, forcing cardinality to 16). Even though it should have worked, there seems to be some integer overflowing details which I am not understanding (despite "Prevent overflows: Yes" in the options).

* A.1.2 Relational and Predicate Calculus Styles

#+begin_src
assert nonempty {
  all r: univ -> univ | some r iff
    some x, y: univ | x -> y in r
}
assert transitive {
  all r: univ -> univ | r.r in r iff
    all x,y,z: univ | x->y in r and y->z in r => x->z in r
}
assert irreflexive {
  all r: univ -> univ | no iden & r iff
    all x: univ | x->x not in r
}
assert symmetric {
  all r: univ -> univ | r in ~r iff
    all x,y: univ | x->y in r => y->x in r
}
assert functional {
  all r: univ -> univ | ~r.r in iden <=>
    all x,y,y': univ | x->y in r and x->y' in r implies y=y'
}
assert injective {
  all r: univ -> univ | r.~r in iden <=>
    all x,x',y: univ | x->y in r and x'->y in r implies x=x'
}
assert total {
  all r: univ -> univ | univ in r.univ <=>
    all x: univ | some y: univ | x->y in r
}
assert surjective {
  all r: univ -> univ | univ in univ.r <=>
    all y: univ | some x: univ | x->y in r
}

check nonempty
check transitive --for 3 but 0 Int
check irreflexive
check symmetric
check functional --for 0 but 1 Int
check injective --for 0 but 1 Int
check total
check surjective
#+end_src

Note in this book, injective is a property of relations in general. In another book (/How to prove it/), injective is a property of specific relations only, ie those that are functions (functional and total).

* A.1.4 Refactoring Navigation Expressions

#+begin_src
assert union {
  all s: set univ | all p,q: univ -> univ | s.(p+q) = s.p + s.q
}
assert intersection {
  all s: set univ | all p,q: univ -> univ | s.(p& q) = s.p & s.q
}
assert difference {
  all s: set univ | all p,q: univ -> univ | s.(p-q) = s.p - s.q
}

check union for 4 but 0 Int
check intersection for 2 but 0 Int
check difference for 2 but 0 Int
#+end_src

Join seems to be distributive over union: No counterexample is found.

Join is not distributive over intersection: Alloy finds a counterexample. Even with only two elements. Namely: s={(0),(1)} p={(0,0)} q={(1,0)}. p&q is empty, but s.p&s.q={(0)}. Alloy's evaluator is super convenient for checking these values of the counterexample.

Join is not distributive over difference. Counterexample with only two elements: s={(0),(1)}, p={(0,0),(0,1)}, q={(1,1),(1,0)}. Then p-q=p, s.(p-q)=s.p={(0),(1)}. However s.p-s.q={}.

* A.1.5 Characterizing Trees

#+begin_src
pred isTree(r: univ -> univ) {
  some univ

  no x: univ | some x.^r & x  -- no cycle
  all x: univ | lone r.x      -- each node has at most one parent
  one x: univ | no r.x        -- exactly one root node
}

run isTree for 4 but 0 Int
#+end_src

No cycle: no node is in its transitive closure through r.

In Alloy's visualizer, Command+N shows more instances.

* A.1.6 Spanning Trees

For a directed graph and directed tree (with isTree from A.1.5):

#+begin_src
pred spans(g1,g2: univ -> univ) {
  g1 in g2
}
pred show(g,t1,t2: univ -> univ) {
  spans [t1,g] and isTree[t1]
  spans [t2,g] and isTree[t2]
  t1 not = t2
}
run show for 3 but 0 Int
#+end_src

For an undirected graph but still a directed tree, simply add ~g in g.

The characterization of [[https://en.wikipedia.org/wiki/Tree_%28graph_theory%29][undirected tree is different]] (in particular, it doesn't require a single root). I followed the [[http://cs.brown.edu/courses/cs195y/2017/assignments/alloy-2.html][hint there]] :

#+begin_src
pred isUndirectedTree(r: univ -> univ) {
  ~r in r  -- symmetric
  all u,v: univ { u != v => u->v in ^r }  -- connected
  all u,v: univ { u->v in r => u->v not in ^(r - u->v) }
    -- no other path, ie acyclic
  no iden & r  -- no cycle on self
}

run isUndirectedTree for 4 Univ, 0 Int
#+end_src

* A.1.7 Characterizing Rings

#+begin_src
sig Node {
  next: set Node
}

pred isRing() {
  all n,n': Node { n->n' in ^next }  -- connected
  all n: Node { one n.next }  -- single next element
}

run isRing for exactly 4 Node
#+end_src
