#+TITLE: Circumference of an ellipse
#+DATE: [2019-04-17 Wed]

The length of an arc $S$ is derived in polar coordinates in /Calculus made easy/ from the infinitely small right angle triangle $ds^2 = (rd\theta)^2 + dr^2$ :

\begin{align*}
S &= \int ds \\
  &= \int ((rd\theta)^2 + dr^2)^{\frac{1}{2}} \\
  &= \int \left(r^2 + \left(\frac{dr}{d\theta}\right)^2\right)^\frac{1}{2} d\theta.
\end{align*}

For an ellipse,

\begin{align*}
r^2 &= a^2\cos^2\theta+b^2\sin^2\theta \\
2\,r\,dr &= -2\,a^2\cos\theta\sin\theta\,d\theta+2\,b^2\sin\theta\cos\theta\,d\theta \\
\frac{dr}{d\theta} &= (b^2-a^2)\frac{\cos\theta\sin\theta}{r}
\end{align*}

For circles, $r$ is constant. So $\frac{dr}{d\theta} = 0$. Hence $S = \int_0^{2\pi} r d\theta = 2\pi r$, the formula for the circumference of a circle.

Apparently though, there is no such thing as an expression for the general case using the "usual functions". I am not even sure what that means, but I am guessing this : the circumference of an ellipse cannot be expressed as a finite combination of arithmetic operators and trigonometric functions.
