#+TITLE: Covariance and correlation
#+DATE: [2019-11-12 Tue]

$Cov(X,Y)=E((X-E(X))(Y-E(Y)))$. Using linearity of expectation, this is $Cov(X,Y)=E(XY)-2\,E(X)E(Y)+E(X)E(Y)=E(XY)-E(X)E(Y)$. If $X$ and $Y$ are independent (meaning outcomes of one are independent with all outcomes of the other), the following holds :

\begin{align*}
E(XY)
&=\sum_{(k,k')} x_k\,y_{k'}\,P(X=x_k,Y=y_{k'})\\
&=\sum_{(k,k')} x_k\,y_{k'}\,P(X=x_k|Y=y_{k'})\,P(Y=y_{k'})\\
&=\sum_{(k,k')} x_k\,y_{k'}\,P(X=x_k)\,P(Y=y_{k'})\\
&=\sum_k x_k P(X=x_k) \sum_{k'} y_{k'} P(Y=y_{k'})\\
&=E(X)E(Y)\\
\end{align*}

I.e., if $X$ and $Y$ are independent, $E(XY)=E(X)E(Y)$ and $Cov(X,Y)=0$ (but converse not true). A formula where this is handy is this one :

\begin{align*}
Var(X+Y)
&=E\left((X+Y-E(X+Y))^2\right)\\
&=E\left((X-E(X)+Y-E(Y))^2\right)\\
&=E\left((X-E(X))^2+(Y-E(Y))^2-2\,(X-E(X))(Y-E(Y))\right)\\
&=Var(X)+Var(Y)-2\,Cov(X,Y)\\
&=Var(X)+Var(Y)
\end{align*}

I.e., if $X$ and $Y$ are independent, $Var(X+Y)=Var(X)+Var(Y)$. $Var$ doesn't scale with a scalar, so there is no claim of linearity. However, saying "$Var$ is /additive/" is correct (when adding independent random variables). For example, the variance of the number of heads in 100 independent fair coin tosses is 100 times the variance of a single fair coin toss, i.e. $100\cdot\left(0.5-0.5^2\right)=25$. It's way simpler to compute variance that way than to consider the 100 tosses as one outcome.

Finally, correlation : $corr(X,Y)=\frac{Cov(X,Y)}{\sqrt{Var(X)Var(Y)}}$. In particular, since $Cov(X,X)=Var(X)$, $corr(X,X)=1$. A random variable is perfectly correlated with itself.

