#+TITLE: Functions
#+DATE: [2021-01-02 Sat]

Section 5.1 of /How to prove it/.

* Definitions
- What is a function from A to B? A function is a /relation/ from A to B where every element of A appears exactly once. ∀x ∈ A (∃!y ∈ B ((x,y) ∈ f)).
- What is the notation for indicating f is a function from A to B? f : A → B.

When taught functions at school at 14, I was told that only one image value can be associated to a given antecedent value. Now I enjoy seeing how they're defined as a special case of relations. Given that it's a relation, a function is also a set, and can be handled as such, for example : (2,4) ∈ f where f = {(x,y) ∈ ℝ^2 | y = x^2}.

* Theorems
- 5.1.4 f and g functions from A to B. If ∀x ∈ A (f(x) = g(x)), then f = g.

* Practice
** N the set of all countries and C the set of all cities. Let L = {(c,n) ∈ C × N | the city c is in the country n} and H = {(n,c) ∈ N × C | the capital of country n is city c}. Describe L ∘ H and H ∘ L.

L ∘ H = {(n,m) ∈ N × N | countries n and m are the same country} = i_N.

H ∘ L = {(c,d) ∈ C × C | city d is the capital of the country city c is in}.

** Suppose f : A → B and C ⊆ A. The set f ∩ (C × B), which is a relation from C to B, is called the /restriction/ of f to C, and is sometimes denoted f ↾ C. (a) Prove that f ↾ C is a function from C to B and that for all c ∈ C, f(c) = (f ↾ C)(c). (b) Suppose g : C → B. Prove that g = f ↾ C iff g ⊆ f. (c) Let g = {(x,y) ∈ ℤ × ℝ | y = 2x + 3} and h = {(x,y) ∈ ℝ × ℝ | y = 2x + 3}. Prove g = h ↾ ℤ.

(a) Look at the goal, ie the definition of function. You need to prove that for every x ∈ C there is a unique y ∈ B such that (x,y) ∈ f ↾ C.

Existence. Let x ∈ C. Since C ⊆ A, x ∈ A. Because f is a function from A to B, ∃!y ∈ B ((x,y) ∈ f). Since x ∈ C, (x,y) ∈ f but also (x,y) ∈ C × B, ie (x,y) belongs to the intersection, ie to f ↾ C.

Uniqueness. Let (x,y) ∈ f ↾ C and (x,y') ∈ f ↾ C. Since f ↾ C ⊆ f, it follows that (x,y) ∈ f and (x,y') ∈ f. By definition of function, it follows that y = y'.

Let x ∈ C. Then ∃!y ∈ B ((x,y) ∈ f ↾ C), ie (x,y) ∈ f and (x,y) ∈ C × B. Then (f ↾ C)(x) = y = f(x).

(b) (→) Suppose g = f ↾ C. Then g = f ∩ (C × B) ⊆ f.

(←) Suppose g ⊆ f, prove g = f ↾ C. Let x ∈ C. Since g ⊆ f, g(x) = f(x). But since x ∈ C, (x,f(x)) ∈ C × B and (x,f(x)) ∈ f, hence (x,f(x)) ∈ f ↾ C. Hence (f ↾ C)(x) = f(x) = g(x). Since it's true for all x ∈ C, g = f ↾ C (by 5.1.4).

(c) h ↾ ℤ = h ∩ (ℤ × ℝ) = {(x,y) ∈ ℝ × ℝ ∩ ℤ × ℝ | y = 2x + 3} = {(x,y) ∈ ℤ × ℝ | y = 2x + 3} = g.

** Suppose R is a relation from A to B, S is a relation from B to C, Ran(R) = Dom(S) = B, and S ∘ R : A → C. (a) Prove that S : B → C. Show that R need not be a function.

(a) Prove that S is a function from B to C. Ie that for all x ∈ B, ∃!y ∈ C ((x,y) ∈ S).

Existence. Implied by Dom(S) = B.

Uniqueness. Let (x,y) ∈ S and (x,y') ∈ S. Since Ran(R) = B, ∃a ∈ A ((a,x) ∈ R). Then (a,y) and (a,y') belong to S ∘ R. Since S ∘ R is a function, it must be that y = y'.

(b) A = {1}, B = {2,3}, C = {4}. S = {(2,4),(3,4)}. R = {(1,2),(1,3)}. Then S ∘ R = {(1,4)}, which is a function from A to C, while R is not a function.

** Suppose f : A → B and R is a relation on A. Define a relation S on B as follows : S = {(x,y) ∈ B × B | ∃u ∈ A ∃v ∈ A (f(u) = x ∧ f(v) = y ∧ (u,v) ∈ R)}. If R is, must S also be (a) reflexive (b) symmetric (c) transitive ?

(a) No, there's nothing constraining S to include all elements of B. Let A = {1}, B = {2,3}, f = {(1,2)}, R = {(1,1)}. Then S = {(2,2)}. R is reflexive, but S isn't since (3,3) ∉ S.

(b) Suppose (x,y) ∈ S. Then let u ∈ A and v ∈ A such that f(u) = x and f(v) = y and (u,v) ∈ R. Since R is symmetric, (v,u) ∈ R and f(v) = y and f(u) = x, hence (y,x) ∈ S. Symmetry is preserved.

(c) A tentative proof would start by supposing (x,y) ∈ S and (y,z) ∈ S. However it needs not be the case that ∃v ∈ A (f(v) = y) that is both in the domain and range of R. Let A = {0,1,2}, B = {3,4}, f = {(0,3),(1,4),(2,4)}, R = {(0,2),(1,2),(1,0)}. Then S = {(3,4),(4,4),(4,3)}. R is transitive, but S isn't since (3,3) ∉ S.

** Let F = {f | f : ℤ^{+} → ℝ}. For g ∈ F, we define the set O(g) as follows : O(g) = {f ∈ F | ∃a ∈ ℤ^{+} ∃c ∈ ℝ^{+} ∀x > a (|f(x)| ≤ c|g(x)|)} (ie if f ∈ O(g), f is big-oh of g). (a) Let f ∈ F and g ∈ F defined as f(x) = 7x + 3 and g(x) = x^2. Prove that f ∈ O(g), but g ∉ O(f). (b) Let S = {(f,g) ∈ F × F | f ∈ O(g)}. Prove that S is a preorder (reflexive and transitive), but not a partial order. (c) Suppose f_1 ∈ O(g) and f_2 ∈ O(g), and s and t are real numbers. Define a function f : ℤ^{+} → ℝ by the formula f(x) = sf_1(x) + tf_2(x). Prove that f ∈ O(g).

(a) To be big-oh of g, we must find a and c such that ∀x > a (|f(x)| ≤ c|g(x)|). If c = 1, |7x + 3| ≤ |x^2| or equivalently 7x + 3 ≤ x^2, ie x^2 - 7x - 3 ≥ 0. The inequality holds for x > 7.

The second statement is a negative statement. Let's try by contradiction. Assume g ∈ O(f). Then we can choose a and c such that ∀x > a (|g(x)| ≤ c|f(x)|), or equivalently ∀x > a (x^2 ≤ c(7x + 3)). Since x ∈ ℤ^{+}, x ≥ 1, and ∀x > a (x^2 ≤ c(7x + 3x) = 10cx). Picking x such that x > 10c (and x > a), we have also x^2 > 10cx, contradicting the earlier inequality. Hence our assumption must be false: g ∉ O(f).

(b) Preorder:

- Reflexive: Let h ∈ F. ∀x > 1 (|h(x)| ≤ 1.|h(x)|). Hence h ∈ O(h), and (h,h) ∈ S.
- Transitive: Let (h,i) ∈ S and (i,j) ∈ S. Let (a,a') ∈ (ℤ^{+})^2 and (c,c') ∈ (ℝ^{+})^2 such that ∀x > a (|h(c) ≤ c|i(x)|) and ∀x > a' (|i(x)| ≤ c'|j(x)|). Then ∀x > max(a,a') (|h(x) ≤ c|i(x)| ≤ cc'|j(x)|). Hence h ∈ O(j) and (h,j) ∈ S.

Not a partial order:

Given S is a preorder, it must fail the remaining condition for being a partial order: antisymmetry. Let f ∈ F and g ∈ F be defined as f(x) = 7x + 3 and g(x) = 7x + 2. ∀x > 1 (|f(x)| ≤ 2|g(x)| ∧ |g(x)| ≤ 1|f(x)|). Hence (f,g) ∈ S and (g,f) ∈ S, but f ≠ g.

(c) Let (a,a') ∈ (ℤ^{+})^2 and (c,c') ∈ (ℝ^{+})^2 such that ∀x > a (|f_1(x)| ≤ c|g(x)|) and ∀x > a' (|f_2(x)| ≤ c'|g(x)|). Hence ∀x > max(a,a') (|s||f_1(x)| + |t||f_2(x)| ≤ (c|s| + c'|t|) |g(x)|). By the triangle inequality, |sf_1(x) + tf_2(x)| ≤ |s||f_1(x)| + |t||f_2(x)|. Combining the two inequalities leads to (sf_1(x) + tf_2(x)) ∈ O(g).

Note this is invalid if s and t are zero, because then c|s| + c'|t| is also, ie not positive as required by the definition of big-oh. So you might change it to c|s| + c'|t| + 1. A reminder to pay attention to assumptions.
