#+TITLE: Generating function
#+DATE: [2020-02-19 Wed]

The common example of generating function is that of the Fibonacci sequence (defined by the recurrence $a_{n+2}=a_{n+1}+a_{n}$, $a_0=0$, $a_1=1$). It isn't obvious at all that you can find a closed-form (non-recursive) expression for $a_{n}$, similar to an arithmetic or geometric recurrence. With the generating function "trick", you can!

An infinitely derivable function $f$ has a unique Taylor series expansion. What if you define the coefficients to be precisely the elements of the Fibonacci sequence? ie :

\begin{align*}
f(x) = \sum_{n=0}^{\infty}\frac{f^{(n)}(0)}{n!}x^n = \sum_{n=0}^{\infty} a_n x^n
\end{align*}

Given the Fibonacci relation :

\begin{align*}
a_{n+2} &= a_{n+1}+a_n \\
a_{n+2} x^{n+2} &= a_{n+1} x^{n+1} x + a_n x^n x^2 \\
\sum_{n=0}^{\infty} a_{n+2} x^{n+2} &= \sum_{n=0}^{\infty} a_{n+1} x^{n+1} x + \sum_{n=0}^{\infty} a_n x^n x^2 \\
\sum_{n=2}^{\infty} a_n x^n &= \sum_{n=1}^{\infty} a_n x^n x + \sum_{n=0}^{\infty} a_n x^n x^2 \\
f(x)-a_1 x-a_0 &= (f(x)-a_0) x + f(x) x^2 \\
f(x) &= \frac{x}{1-x-x^2}, 1-x-x^2 \neq 0.
\end{align*}

$f$ is the generating function for the Fibonacci sequence. The equality between the two forms holds only when the sum converges (eg $x=0$). The equality doesn't hold when the sum diverges (eg $x=1$).

To have an expression for $a_n$, all that's left to do is to find an expression for $\frac{f^{(n)}(0)}{n!}$. Deriving $f(x) = \frac{x}{1-x-x^2}$ a few times shows a pattern leading to the solution. You'll probably need to decompose $f$ into partial fractions first to make deriving manageable.

Another approach to deriving is to recognize $f$ as the sum of two functions of the form $\frac{1}{1-cx}$. That form is very close to $\frac{1}{1-x}$, for which the power series expansion is known. But that approach is of course specific to $f$.
