#+TITLE: Ordered pairs and relations
#+OPTIONS: toc:nil num:nil
#+DATE: [2020-09-10 Thu]

Sections 4.1-4.3 of /How to prove it/.

* Definitions
- Ordered pair ? (a,b).
- Cartesian product A × B ? {(a,b) | a ∈ A ∧ b ∈ B}.
- Truth set of P(x,y), x ∈ A, y ∈ B ? {(a,b) ∈ A × B | P(a,b)}.
- Relation R from A to B ? R ⊆ A × B.
- Domain(R) ? {a ∈ A | ∃b ∈ B ((a,b) ∈ R)}.
- Range(R) ? {b ∈ B | ∃a ∈ A ((a,b) ∈ R)}.
- R^-1 ? {(b,a) ∈ B × A | (a,b) ∈ R}.
- S ∘ R ? {(a,c) ∈ A × C | ∃b ∈ B ((a,b) ∈ R ∧ (b,c) ∈ S)}.
- R is reflexive (on A) ? ∀x ∈ A (xRx). Example : =.
- R is symmetric (on A) ? ∀(x,y) ∈ A × A (xRy → yRx).
- R is transitive (on A) ? ∀(x,y,z) ∈ A^3 (xRy ∧ yRz → xRz).
- Identity (on A) ? {(x,x) | x ∈ A}.

* Theorems
- 4.2.5 (S ∘ R)^-1 = R^-1 ∘ S^-1
- 4.3.4 R is symmetric iff R = R^-1

* Practice
** Prove R is reflexive iff i_A ⊆ R (R relation on A)

→ Suppose R is reflexive. Prove i_A ⊆ R, ie ∀(x,y) ∈ i_A, (x,y) ∈ R. Let (x,y) ∈ i_A be arbitrary. Since (x,y) ∈ i_A, (x,y) = (x,x). But since R is reflexive on A, (x,x) ∈ R, and hence (x,y) ∈ R. Since (x,y) was an arbitrary object of i_A, it's true for all such objects, proving the inclusion.

← Suppose i_A ⊆ R. Prove R is reflexive, ie ∀x ∈ A (xRx). Let x be an arbitrary object of A. Then (x,x) ∈ i_A. But then since i_A ⊆ R, (x,x) ∈ R.

** Suppose S is a relation on A. Let D = Domain(S) and R = Range(S). Prove that i_D ⊆ S^-1 ∘ S and i_R ⊆ S ∘ S^-1

Note S ⊆ A × A, and more precisely S ⊆ D × R. R here is a subset of A, and not a relation. Then S^-1 ∘ S ⊆ D × D (the rightmost relation is used first).

Let (x,y) ∈ i_D be arbitrary. Prove (x,y) = (x,x) ∈ S^-1 ∘ S. Since x ∈ D, ∃z ∈ R ((x,z) ∈ S). It follows that (z,x) ∈ S^-1. Then (x,z) ∈ S ∧ (z,x) ∈ S^-1, ie (x,x) ∈ S^-1 ∘ S.

Similar reasoning for i_R.

** Suppose R_1 and R_2 are relations on A. If R_1 and R_2 are reflexive / symmetric / transitive, must R_1 ∪ R_2 also be ?

(a) ∀x ∈ A (xR_{1}x ∧ xR_{2}x), prove ∀y ∈ A (y(R_1 ∪ R_2)y). Let y ∈ A be arbitrary. Then (y,y) ∈ R_1 since R_1 is reflexive, and hence (y,y) ∈ R_1 ∪ R_2. Hence their union must also be reflexive.

(b) Let (x,y) ∈ R_1 ∪ R_2 be arbitrary. Case (x,y) ∈ R_1. Then (y,x) ∈ R_1 since R_1 is symmetric, and hence (y,x) ∈ R_1 ∪ R_2. Case (x,y) ∈ R_2, same reasoning. This exhausts all cases. Since (x,y) was arbitrary, it's true for all (x,y) elements of the union, proving that the union is symmetric.

(c) R_1={(1,2)}, R_2={(2,3)}. They're individually transitive, but their union isn't.

** Suppose R and S are symmetric relations on A. Prove that R ∘ S is symmetric iff R ∘ S = S ∘ R.

Because they're symmetric, R = R^-1 and S = S^-1 (the converse is true as well). R ∘ S is symmetric iff R ∘ S = (R ∘ S)^-1, equivalent to R ∘ S  = (R ∘ S)^-1 = S^-1 ∘ R^-1 = S ∘ R.

Commentary: you could have used the definition of a symmetric relation, but the proof would have been lengthier. Here you're using an equivalent characterization of symmetry, and a reexpression of the inverse of composition (both proved in the book). Hence the need to know not only definitions but also theorems that build on them.

** Suppose R is a relation on A. Let B = {X ∈ 𝒫(A) | X ≠ ∅)}, and define a relation S on B as follows: S={(X,Y) ∈ B × B | ∀x ∈ X ∀y ∈ Y (xRy)}. Prove that if R is transitive, then so is S. Why did the empty set have to be excluded from the set B to make this proof work?

Reuse proof strategies from chapter 3. Given: R is transitive. Goal: S is transitive. Focus on the definition of the goal. S is transitive if ∀X ∈ B ∀Y ∈ B ∀Z ∈ B ((X,Y) ∈ S ∧ (Y,Z) ∈ S → (X,Z) ∈ S). Arbitrary object on goal: let (X,Y,Z) ∈ B^3, prove (X,Y) ∈ S ∧ (Y,Z) ∈ S → (X,Z) ∈ S (notice you got rid of the quantifiers). Assume (X,Y) ∈ S ∧ (Y,Z) ∈ S, prove (X,Z) ∈ S. Focus on the definition of the new goal, (X,Z) ∈ S: ∀x ∈ X ∀z ∈ Z (xRz). Arbitrary object on the new goal: let (x,z) ∈ (X,Z), prove xRz (you got rid of the quantifiers again). Universal instantiation on given: let y ∈ Y. This is possible because Y ∈ B, and B does not include the empty set. But (X,Y) ∈ S ∧ (Y,Z) ∈ S, so xRy ∧ yRz. And since R is transitive, you finally have xRz. Backing up: since (x,z) was an arbitrary element of (X,Z), you have (X,Z) ∈ S, and since (X,Y,Z) was an arbitrary element of B^3, you conclude S is transitive.

Now let's show that the proof is invalid if B includes ∅. The proof is invalid if there is a way for the formula (R transitive → S transitive) to come out false. Note the formula doesn't need to always be false, it just needs to come out false in one instance. Implication comes out false when the antecedent is true but the consequent is false (see [[./proof-strategies-revisited.org][Proof strategies revisited]]). So, assuming R is transitive (and B includes ∅), is there a way for S to not be transitive?
- ¬(S transitive)
- ↔ ¬(∀X ∈ B ∀Y ∈ B ∀Z ∈ B ((X,Y) ∈ S ∧ (Y,Z) ∈ S → (X,Z) ∈ S))
- ↔ ∃X ∈ B ∃Y ∈ B ∃Z ∈ B ¬((X,Y) ∈ S ∧ (Y,Z) ∈ S → (X,Z) ∈ S)
- ↔ ∃X ∈ B ∃Y ∈ B ∃Z ∈ B ((X,Y) ∈ S ∧ (Y,Z) ∈ S ∧ (X,Z) ∉ S)
If you choose Y = ∅, then it is the case that (X,∅) ∈ S ∧ (∅,Z) ∈ S (for all with empty set being true). Let A = {1,2}, R = {(1,1),(1,2)}, R is transitive. B = {∅,{1},{2},{1,2}}. X = {2}, Z = {1}. Then (X,Z) ∉ S since (2,1) ∉ R.

** Suppose A is a set, and F ⊆ 𝒫(A). Let R = {(a,b) ∈ A × A | for every X ⊆ A \ {a,b}, if X ∪ {a} ∈ F then X ∪ {b} ∈ F}. Show that R is transitive.

Show that ∀x ∈ A ∀y ∈ A ∀z ∈ A, (x,y) ∈ R ∧ (y,z) ∈ R → (x,z) ∈ R. Let (x,y,z) ∈ A^3 (arbitrary object on goal), show the implication is true. Suppose (x,y) ∈ R ∧ (y,z) ∈ R, show (x,z) ∈ R. In other words, show ∀X ⊆ A \ {x,z}, X ∪ {x} ∈ F → X ∪ {z} ∈ F. Let X ⊆ A \ {x,z} (arbitrary object on new goal), show X ∪ {x} ∈ F → X ∪ {z} ∈ F. Suppose X ∪ {x} ∈ F, show X ∪ {z} ∈ F. But (x,y) ∈ R, so ∀X ⊆ A \ {x,y}, X ∪ {x} ∈ F → X ∪ {y} ∈ F.

Case y ∉ X. Then since X ∪ {x} ∈ F, it follows X ∪ {y} ∈ F. Then since (y,z) ∈ R, it follows similarly X ∪ {z} ∈ F. Case y ∈ X. Let X' = (X ∪ {z}) \ {y}. Then X' ∪ {x} ∈ F → X' ∪ {y} ∈ F (= X ∪ {z} ∈ F, the last goal). Show X' ∪ {x} ∈ F.

Let X'' = (X ∪ {x}) \ {y}. Then X'' ∪ {y} ∈ F (= X ∪ {x} ∈ F) → X'' ∪ {z} ∈ F. But since X ∪ {x} ∈ F, X'' ∪ {z} ∈ F. But then X'' ∪ {z} = X' ∪ {x}, so X' ∪ {x} ∈ F, completing the proof.

* Conclusion

In general, focus on the goal, and in particular its definition. The given is considered after, to prove the goal. Also, rid yourself of quantifiers using "arbitrary object" on goal and "universal instantiation" on given (see infer and goal strategies in Proof Designer).

Knowing theorems on top of definitions is useful for some proofs.
