#+TITLE: Probabilité de couvrir le Goncourt
#+DATE: [2020-06-14 Sun]

Le Goncourt se déroule en 3 sélections précédant l'annonce du vainqueur. À la première sélection, le jury retient 15 livres. Aux suivantes, il en retient: 9 ou 8, puis 4 (les finalistes), et enfin 1 livre (le vainqueur).

Quelle est la probabilité d'avoir lu les livres sélectionnés ? On choisit un modèle ayant les paramètres suivants : pour chaque sélection il y a $n$ livres avant, et $m$ après (le modèle ne s'applique pas à la première selection). On a lu $r$ livres sur les $n$. Par exemple à la deuxième sélection, il y avait $n=15$ livres avant, $m=9$ livres après, et on en a lu disons $r=5$.

On fait la supposition qu'il n'y a pas d'information supplémentaire, et que la sélection du Goncourt aussi bien que les livres qu'on a choisi de lire sont complètement arbitraires : un livre n'est pas favori par rapport à un autre.

Soit $L$ l'ensemble de taille $n$ des livres avant sélection. Soit $S$ l'ensemble des sélections possibles : les sous-ensembles de $L$ à taille $m$. Soit $R$ l'ensemble des choix possibles de lecture : les sous-ensembles de $L$ à taille $r$. L'univers $\Omega$ de cette expérience probabiliste est $S \times R$. En reprenant l'exemple, $|S|={15 \choose 9}$, $|R|={15 \choose 5}$, et $|\Omega|$ $=|S| \cdot |R|$ $={15 \choose 9} \cdot {15 \choose 5}$. Chaque paire de l'univers est équiprobable, de probabilité $|\Omega|^{-1}$.

On considère $X : \Omega \rightarrow [0..5]$ la variable aléatoire indiquant le nombre de livres qui ont été à la fois lus et sélectionnés. $P(X=5)$ est donc la probabilité que les 5 livres lus parmi les 15 ont également été sélectionnés. Pour chacune des ${15 \choose 9}$ sélections de 9 livres, il y a $9 \choose 5$ manière d'avoir lu 5 livres qui ont été sélectionnés. Chaque paire étant équiprobable :

\begin{align*}
P(X=5) = \frac{{15 \choose 9}{9 \choose 5}}{{15 \choose 9}{15 \choose 5}}
       = \frac{{9 \choose 5}}{{15 \choose 5}}
\end{align*}

Qu'en est-il de seulement 4 livres sélectionnés sur les 5 lus ? Pour chacune des ${15 \choose 9}$ sélections de 9 livres, il y a ${9 \choose 4}$ manières d'avoir lu 4 livres qui ont été sélectionnés. Mais il y a aussi ${15-9 \choose 1}$ manières d'avoir lu 1 livre qui n'a pas été sélectionné.

\begin{align*}
P(X=4) = \frac{{15 \choose 9}{9 \choose 4}{15-9 \choose 1}}{{15 \choose 9}{15 \choose 5}}
       = \frac{{9 \choose 4}{15-9 \choose 1}}{{15 \choose 5}}
\end{align*}

Dans le premier cas qu'on a considéré avec 5 livres lus et sélectionnés, il y avait ${15-9 \choose 0}$ manières d'avoir lu 0 livre qui n'a pas été sélectionné, soit 1. On a donc, en généralisant ($k$ le nombre de livres à la fois lus et sélectionnés) :

\begin{align*}
P(X=k) = \frac{{m \choose k}{n-m \choose r-k}}{{n \choose r}}
\end{align*}

On peut vérifier qu'en sommant les probabilités pour $k$ de 0 au nombre lu, on a bien 1 (axiome de probabilité) :

\begin{align*}
\sum_{k=0}^{r} P(X=k) &= \frac{1}{{n \choose r}} \sum_{k=0}^{r} {m \choose k}{n-m \choose r-k} \\
	      	     &= \frac{1}{{n \choose r}} {m+n-m \choose r} \\
		     &= 1
\end{align*}

On passe à la deuxième ligne en reconnaissant l'identité de Vandermonde. Si $r>m$, c'est-à-dire qu'on a lu plus de livres que de sélectionnés, on peut simplement échanger $m$ et $r$ dans la formule. Le raisonnement est le même.

En ayant lu 5 livres, la probabilité d'avoir lu au moins 3 livres qui ont été sélectionnés est $P(X \geq 3)$ $= P(X=3)+P(X=4)+P(X=5)$, environ 71%. Si ensuite on en lit 3 additionnels, la probabilité d'avoir lu les 4 finalistes est $P(X'=4)$ $= {6 \choose 4}{9-6 \choose 4-4}{9 \choose 4}^{-1}$, environ 12%. La probabilité d'avoir lu au moins 3 finalistes monte à 60%.

Ce modèle fait une supposition simplificatrice : chaque livre a autant de chance qu'un autre d'être sélectionné. De même on a supposé qu'on a choisit les livres qu'on a lus sans préférence. Dans les faits, un livre chez Gallimard a beaucoup plus de chance d'être sélectionné qu'un livre dans une plus petite maison d'édition.
